name: Test
on:
  push:
  pull_request:

permissions: {}

jobs:
  save-patches:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - run: make update
      - name: Generic commit
        run: |
             cd beamer
             echo "test" >> p1500-serial-codes.md
             git add p1500-serial-codes.md
             git config user.name "test"
             git config user.email "test@example.org"
             git commit -m "test"
             git tag generic
      - name: Setup Git identity for specific commits
        run: |
             cd beamer
             git config user.name "specific"
             git config user.email "test@example.com"
      - name: Specific commit 1
        run: |
             cd beamer
             echo "specific" > README.md
             git add README.md
             git commit -m "this is very specific"
      - name: Specific commit 2
        run: |
             cd beamer
             echo "empty" >> empty
             git add empty
             git commit -m "new empty file" 
             git tag specific
      - name: Save patches
        run: |
             make save
             ls -R patches
