name: Test
on:
  push:
  pull_request:

permissions: {}

jobs:
  save-patches:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - run: make update
      - name: Generic commit
        run: |
             cd beamer
             echo "test" >> p1500-serial-codes.md
             git add p1500-serial-codes.md
             git config user.name "test"
             git config user.email "test@example.org"
             git commit -m "test"
             git tag generic
      - name: Setup Git identity for specific commits
        run: |
             cd beamer
             git config user.name "specific"
             git config user.email "test@example.com"
      - name: Specific commit 1
        run: |
             cd beamer
             echo "specific" > README.md
             git add README.md
             git commit -m "this is very specific"
      - name: Specific commit 2
        run: |
             cd beamer
             echo "empty" >> empty
             git add empty
             git commit -m "new empty file" 
             git tag specific
      - name: Save patches
        run: |
             make save
             ls -R patches
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: "patches"
          path: "./patches"
  apply-patches:
    runs-on: ubuntu-latest
    needs: save-patches
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          name: "patches"
          path: "./patches"
      - name: "List patch files"
        run: ls -lhR patches
      - run: make update
      - name: Apply generic
        run: |
             make generic
             pushd beamer
             exec 5>&1
             GIT_OUTPUT=$(git log -2 | tee /dev/fd/5)
             count=$(echo "$GIT_OUTPUT" | grep -c "test@example.org")
             [ "$count" = 1 ] || { printf "missing generic commit, found %s", $count; exit 1; }
             popd
      - name: Apply specific
        run: |
             make specific
             pushd beamer
             exec 5>&1
             GIT_OUTPUT=$(git log -4 | tee /dev/fd/5)
             count=$(echo "$GIT_OUTPUT" | grep -c "test@example.org")
             [ "$count" = 1 ] || { printf "missing generic commit, found %s", $count; exit 1; }
             count=$(echo "$GIT_OUTPUT" | grep -c "test@example.com")
             [ "$count" = 2 ] || { printf "missing specific commit(s), found %s", $count; exit 1; }
             popd
      - name: Reset
        run: |
             make update
             pushd beamer
             git log -2
             popd
      - name: Apply specifc w/ generic dependency
        run: |
             make specific
             pushd beamer
             exec 5>&1
             GIT_OUTPUT=$(git log -4 | tee /dev/fd/5)
             count=$(echo "$GIT_OUTPUT" | grep -c "test@example")
             [ "$count" = 3 ] || { printf "missing commit(s), found %s", $count; exit 1; }
             popd